name: manual testing from dev
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'dev'
        type: environment
jobs:
  build_code:
    runs-on: ubuntu-latest
    steps:
      - run: echo "triggered manually..."
      
# name: Build and deploy .NET Core application to Web App roxie-testapi-as
# on:
#  push:
#    branches:
#    - master
