name: manual testing from dev
on:
  workflow_dispatch:
  schedule:
    - cron: '10 0 * * *'
  
jobs:
  build_code:
    runs-on: ubuntu-latest
    steps:
      - run: echo "triggered manually..."
      
# name: Build and deploy .NET Core application to Web App roxie-testapi-as
# on:
#  push:
#    branches:
#    - master
