name: manual testing from Testing branch
on:
  workflow_dispatch:
  
jobs:
  build_code:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch
        if: ${{ github.ref != 'refs/heads/testing' }}
        run: |
          echo "Deploying to dev only from develop branch.  Current branch is: $GITHUB_REF"
          exit 1
                
      - name: Exit if not on develop branch
        if: github.ref != 'refs/heads/develop'
        run: |
          echo "Deploying to dev only from develop branch.  Current branch is: $GITHUB_REF"
          exit 1
          
