name: manual testing from Testing branch
on:
  workflow_dispatch:
  
jobs:
  build_code:
    runs-on: ubuntu-latest
    steps:
      - run: echo "build triggered manually..."
      
      - name: Exit if not on master branch
        if: github.ref != 'refs/heads/develop'
        run: |
          echo "Deploying to dev only from develop branch.  Current branch is: $GITHUB_REF"
          exit 1
          
