name: Build and deploy .NET Core application to Web App roxie-testapi-as
on:
  push:
    branches:
    - master
env:
  AZURE_WEBAPP_NAME: roxie-testapi-as
  AZURE_WEBAPP_PACKAGE_PATH: "."
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 8.0.x
  WORKING_DIRECTORY: TestingApi
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Check out the repo
    - uses: actions/checkout@v4
    
    # Setup .NET Core SDK
    - name: Set up .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_CORE_VERSION }}
    
    # Run dotnet build and publish    
    - name: Build
      run: |
        dotnet build --configuration Release
        # dotnet publish -c Release --property:PublishDir='${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/testapi'
        dotnet publish -c Release
        
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
            app-name: ${{ env.AZURE_WEBAPP_NAME }}
            publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
            package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

    - name: Azure login
      uses: azure/login@v2
      with:
          client-id: "876e75f9-1083-48a8-9011-1bf54582dfcb"  # ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: "4baf6c69-c1dd-43dd-8fc6-e1ef405f2633"  # "${{ secrets.AZURE_TENANT_ID }}
          subscription-id: "29c2e57b-d84c-41de-bc3e-015e798a1c58"  # ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Azure CLI script
      uses: azure/cli@v2
      with:
          azcliversion: latest
          inlineScript: |
            az account show

#jobs:
#  build-and-deploy:
#    runs-on: self-hosted
#    steps:
#      - name: Azure login
#        uses: azure/login@v2
#        with:
#          auth-type: IDENTITY
#          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
#          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
#          enable-AzPSSession: true

      # Azure CLI Action only supports linux self-hosted runners for now.
      # If you want to execute the Azure CLI script on a windows self-hosted runner, you can execute it directly in `run`.
#      - name: Azure CLI script
#        uses: azure/cli@v2
#        with:
#          azcliversion: latest
#          inlineScript: |
#            az account show

#      - name: Azure PowerShell script
#        uses: azure/powershell@v2
#        with:
#          azPSVersion: "latest"
#          inlineScript: |
#            Get-AzContext
#            Get-AzResourceGroup
